export const newsletterMeta = [
  {
    file: 'why-everyone-looks-the-same',
    published: true,
    title: 'Why everyone looks the same now.',
    tag: 'From the Closet · Issue 015',
    date: '2026-06-16',
    readTime: '3 min',
    image: '/newsletter-images/clones.gif',
    summary: "It isn't a trend. It's the machinery underneath.",
  },
  {
    file: 'clothes-youve-never-worn',
    published: true,
    title: 'Some of your clothes have never been worn.',
    tag: 'From the Closet \u00b7 Issue 011',
    date: '2026-06-02',
    readTime: '3 min',
    image: '/newsletter-images/closet.gif',
    summary: 'You know exactly which ones they are.',
  },
  {
    file: 'excitement-is-a-bad-way-to-shop',
    published: true,
    title: 'Excitement is a bad way to shop.',
    tag: 'From the Closet \u00b7 Issue 013',
    date: '2026-06-09',
    readTime: '4 min',
    image: '/newsletter-images/nothingtowear.gif',
    summary: 'Try these three questions before you pay.',
  },
  {
    file: 'old-money-on-a-student-budget',
    published: true,
    title: 'Old money, on a student budget',
    tag: 'Oro Insiders \u00b7 Issue 003',
    date: '2026-05-06',
    image: '/newsletter-images/recession.webp',
    summary: 'The restraint is the whole point. You already own most of this.',
  },
  {
    file: 'oro-v220',
    published: false,
    title: "Oro knows what it's like outside now.",
    tag: 'From the Closet \u00b7 Issue 009',
    date: '2026-05-30',
    readTime: '2 min',
    summary: "V2.2.0 is out. Here's what changed.",
  },
  {
    file: 'something-real-happened-this-week',
    published: true,
    title: 'We owe you an update.',
    tag: 'Oro Insiders \u00b7 Issue 006',
    date: '2026-05-19',
    image: '/newsletter-images/kibo.webp',
    summary: '600 downloads. V2 is live. A few things we want to say.',
  },
  {
    file: 'the-rule-of-three',
    published: true,
    title: 'The rule of three.',
    tag: 'From the Closet \u00b7 Issue 008',
    date: '2026-05-26',
    readTime: '3 min',
    image: '/newsletter-images/breakfast-at-tiffanys.webp',
    summary: "The best outfits only have three things going on. Here's why that matters.",
  },
  {
    file: 'what-we-mean-by-closet',
    published: true,
    title: 'What we mean by \u201ccloset.\u201d',
    italicTitle: '\u201ccloset.\u201d',
    tag: 'From the Closet \u00b7 Issue 007',
    date: '2026-05-23',
    readTime: '2 min',
    image: '/newsletter-images/closet.webp',
    summary: 'A closet is a memory of who you\u2019ve been. And a clue to who you\u2019re becoming. On the words we kept, the ones we threw out, and why \u201ccloset\u201d won.',
  },
  {
    file: 'what-were-listening-for',
    published: true,
    title: "What we're listening for",
    tag: 'Oro Insiders \u00b7 Issue 001',
    date: '2026-05-01',
    image: '/newsletter-images/csq.webp',
    summary: "A note on why we're starting this \u2014 and what we'll be doing here.",
  },
  {
    file: 'you-already-think-about-it',
    published: true,
    title: 'You already think about it',
    tag: 'Oro Insiders \u00b7 Issue 004',
    date: '2026-05-16',
    image: '/newsletter-images/thrift.webp',
    summary: "Men care. They just won't say it.",
  },
  {
    file: 'you-dont-dress-for-the-life-you-have',
    published: true,
    title: "You don't dress for the life you have.",
    tag: 'From the Closet \u00b7 Issue 014',
    date: '2026-06-13',
    readTime: '4 min',
    image: '/newsletter-images/closet-toss.gif',
    summary: 'You dress for the one in your head.',
  },
  {
    file: 'you-should-be-an-outfit-repeater',
    published: true,
    title: 'You should be an outfit repeater.',
    tag: 'From the Closet \u00b7 Issue 012',
    date: '2026-06-06',
    readTime: '3 min',
    image: '/newsletter-images/repeat.gif',
    summary: 'Seriously, just wear it. Again.',
  },
  {
    file: 'youre-always-dressing-for-someone',
    published: true,
    title: "You're always dressing for someone.",
    tag: 'From the Closet \u00b7 Issue 010',
    date: '2026-05-30',
    readTime: '4 min',
    image: '/newsletter-images/impress.gif',
    summary: "The question isn't whether other people factor in. It's whether you know when they do.",
  },
  {
    file: 'youre-already-dressing-for-the-recession',
    published: true,
    title: "You're already dressing for the recession",
    tag: 'Oro Insiders \u00b7 Issue 002',
    date: '2026-05-02',
    image: '/newsletter-images/kibo.webp',
    summary: 'Why fashion sees it first. The receipts go back to the 18th century.',
  },
  {
    file: 'your-clothes-are-fighting-each-other',
    published: true,
    title: 'Your clothes are fighting each other',
    tag: 'Oro Insiders \u00b7 Issue 005',
    date: '2026-05-17',
    image: '/newsletter-images/005-ill-1-pairs.webp',
    summary: "It's called temperature \u2014 and it changes how you see everything you already own.",
  },
]
