import { test, expect } from './fixtures.js'
import { emptyAnswers, visibleAnswers, validateAnswers } from '../src/components/beta/betaForm.js'

test.beforeEach(async ({ page }) => { await page.emulateMedia({ reducedMotion: 'reduce' }) })

async function next(page) {
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
}

async function fillContact(page) {
  await page.getByLabel('Email address', { exact: true }).fill('beta-test@example.com')
  await page.getByLabel('Phone number', { exact: true }).fill('+1 (416) 555-0123')
}

async function fillRequired(page) {
  await page.getByLabel('Your name', { exact: true }).fill('Jamie')
  await next(page)
  await fillContact(page)
  await next(page)
  await page.getByRole('radio', { name: 'No', exact: true }).check()
  await next(page)
  await page.getByRole('radio', { name: '1–2 days', exact: true }).check()
  await next(page)
  await page.getByLabel('What were you getting dressed for?', { exact: true }).fill('A day at school')
  await page.getByLabel('What were you unsure about?', { exact: true }).fill('Which shoes work with my jeans')
  await next(page)
  await page.getByLabel('Your experience', { exact: true }).fill('Combining colours')
  await next(page)
  await page.getByRole('checkbox', { name: 'Ask a friend', exact: true }).check()
  await next(page)
  await page.getByLabel('What you have in mind', { exact: true }).fill('A second opinion')
  await next(page)
  await page.getByLabel('Your plans', { exact: true }).fill('School and dinner with friends')
  await next(page)
  await page.getByLabel('City and province', { exact: true }).fill('Toronto, Ontario')
  await next(page)
  await next(page)
  await next(page)
  await page.getByRole('radio', { name: 'Website', exact: true }).check()
  await next(page)
}

for (const width of [1440, 390, 320]) {
  test(`story and individual form questions fit ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    const errors = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto('/beta')
    await expect(page.getByRole('heading', { name: 'Help us make Oro yours.' })).toBeVisible()
    await expect(page.getByRole('form')).toHaveCount(0)
    await expect(page.locator('.beta-chapter')).toHaveCount(1)
    await expect(page.locator('.beta-story')).not.toContainText('Whether you’re figuring out')
    await expect(page.locator('.beta-story')).not.toContainText(/imessage beta/i)
    for (let index = 1; index < 7; index++) {
      await page.getByRole('button', { name: 'Next page', exact: true }).click()
      await expect(page.locator('.beta-story-nav button')).toHaveCount(1)
      const arrow = await page.locator('.beta-story-nav button').boundingBox()
      expect(Math.abs(arrow.x + arrow.width / 2 - width / 2)).toBeLessThan(1)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      expect(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight + 1)).toBe(true)
    }
    await expect(page.getByRole('button', { name: 'Request an invite', exact: true })).toBeVisible()
    await page.getByRole('link', { name: 'Skip to the form' }).click()
    await expect(page.getByRole('heading', { name: 'First, what’s your name?' })).toBeVisible()
    await expect(page.getByRole('form').getByRole('group')).toHaveCount(1)
    await expect(page.locator('.beta-question-card')).toHaveCount(0)
    await expect(page.getByRole('radio')).toHaveCount(0)
    await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '1')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(page.getByRole('textbox')).toHaveCount(1)
    await expect(page.getByRole('link', { name: 'Email us', exact: true })).toHaveAttribute('href', 'mailto:sunny@buildingoro.ca')
    await page.getByLabel('Your name', { exact: true }).fill('Jamie')
    await next(page)
    await expect(page.getByRole('heading', { name: 'How can we reach you?' })).toBeVisible()
    await expect(page.getByText('Include your country code. We’re testing over iMessage.')).toHaveCount(0)
    await fillContact(page)
    await next(page)
    await expect(page.getByRole('heading', { name: 'Have you used the Oro app before?' })).toBeVisible()
    await expect(page.getByRole('textbox')).toHaveCount(0)
    const arrow = await page.getByRole('button', { name: 'Continue', exact: true }).boundingBox()
    expect(Math.abs(arrow.x + arrow.width / 2 - width / 2)).toBeLessThan(1)
    await page.goto('/beta#before-send')
    await expect(page.locator('.beta-consent input:checked')).toHaveCount(3)
    await expect(page.locator('.beta-consent')).not.toContainText('Optional')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errors).toEqual([])
  })
}

test('continuing validates only the current question and preserves answers when going back', async ({ page }) => {
  await page.goto('/beta#request')
  await page.getByLabel('Your name', { exact: true }).fill('   ')
  await next(page)
  await expect(page.getByLabel('Your name', { exact: true })).toBeFocused()
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '1')
  await page.getByLabel('Your name', { exact: true }).fill('Jamie')
  await next(page)
  await page.getByLabel('Email address', { exact: true }).fill('invalid-email')
  await next(page)
  await expect(page.getByLabel('Email address', { exact: true })).toBeFocused()
  await expect(page.getByText('Enter a valid email address.')).toBeVisible()
  await expect(page.getByLabel('Email address', { exact: true })).toHaveValue('invalid-email')
  await fillContact(page)
  await next(page)
  await expect(page.getByRole('heading', { name: 'Have you used the Oro app before?' })).toBeFocused()
  await page.getByRole('radio', { name: 'No', exact: true }).check()
  await page.getByRole('button', { name: '← Back', exact: true }).click()
  await expect(page.getByLabel('Email address', { exact: true })).toHaveValue('beta-test@example.com')
  await page.goBack()
  await expect(page.getByRole('radio', { name: 'No', exact: true })).toBeChecked()
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '3')
})

test('keyboard users can choose and change one radio answer', async ({ page }) => {
  await page.goto('/beta#used-oro')
  const yes = page.getByRole('radio', { name: 'Yes', exact: true })
  const no = page.getByRole('radio', { name: 'No', exact: true })
  await yes.focus()
  await page.keyboard.press('Space')
  await expect(yes).toBeChecked()
  await page.keyboard.press('ArrowRight')
  await expect(no).toBeChecked()
  await expect(yes).not.toBeChecked()
  await expect(no).toBeFocused()
  expect(await no.evaluate((input) => getComputedStyle(input.closest('label')).outlineStyle)).toBe('solid')
})

test('optional choices clear and hidden follow-ups do not block continuing', async ({ page }) => {
  await page.goto('/beta#usual-help')
  await page.getByRole('checkbox', { name: 'Ask a friend', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Other', exact: true }).check()
  await next(page)
  await expect(page.getByLabel('What else do you do?', { exact: true })).toBeFocused()
  await page.getByRole('checkbox', { name: 'Other', exact: true }).uncheck()
  await expect(page.getByLabel('What else do you do?', { exact: true })).toHaveCount(0)
  await next(page)
  await expect(page.getByLabel('What you have in mind', { exact: true })).toBeVisible()
  await page.goto('/beta#your-age')
  await page.getByRole('radio', { name: '23–28', exact: true }).check()
  await page.getByRole('button', { name: 'Clear answer' }).click()
  await expect(page.locator('.beta-question input:checked')).toHaveCount(0)
  await next(page)
  await page.getByRole('radio', { name: 'I’d like to self-describe', exact: true }).check()
  await expect(page.getByLabel(/How would you describe your gender/)).toBeVisible()
  await page.getByRole('button', { name: 'Clear answer' }).click()
  await expect(page.getByLabel(/How would you describe your gender/)).toHaveCount(0)
  await next(page)
  await page.getByRole('radio', { name: 'Other', exact: true }).check()
  await next(page)
  await expect(page.getByLabel('Where did you hear about it?', { exact: true })).toBeFocused()
  await page.getByRole('radio', { name: 'Website', exact: true }).check()
  await next(page)
  await expect(page.getByRole('button', { name: 'Request an invite', exact: true })).toBeVisible()
})

test('only terms disable submit; previews preserve answers and no data is sent', async ({ page }) => {
  test.setTimeout(60000)
  const outbound = []
  page.on('request', (request) => {
    if (request.method() === 'POST' || /google-analytics|googletagmanager|posthog/.test(request.url())) outbound.push(request.url())
  })
  await page.addInitScript(() => localStorage.setItem('oro_cookie_consent', 'accepted'))
  await page.goto('/beta#request')
  await fillRequired(page)
  const terms = page.getByRole('checkbox', { name: /By submitting this request/ })
  const futureBeta = page.getByRole('checkbox', { name: /If I’m not invited/ })
  const marketing = page.getByRole('checkbox', { name: /I’d like to receive marketing/ })
  const submit = page.getByRole('button', { name: 'Request an invite', exact: true })
  await expect(terms).toBeChecked()
  await expect(futureBeta).toBeChecked()
  await expect(marketing).toBeChecked()
  await marketing.uncheck()
  await futureBeta.uncheck()
  await expect(submit).toBeEnabled()
  await terms.uncheck()
  await expect(submit).toBeDisabled()
  await terms.check()
  await submit.click()
  await expect(page.getByText('This draft isn’t connected yet.')).toBeVisible()
  await page.getByRole('button', { name: /Preview confirmation/ }).click()
  await expect(page.getByRole('heading', { name: 'Request received :)' })).toBeVisible()
  await expect(page.getByText('Confirmation preview · No request has been saved')).toBeVisible()
  await page.getByRole('button', { name: 'Back to the draft', exact: true }).click()
  await expect(futureBeta).not.toBeChecked()
  await expect(marketing).not.toBeChecked()
  for (let index = 0; index < 5; index++) await page.getByRole('button', { name: '← Back', exact: true }).click()
  await expect(page.getByLabel('Your plans', { exact: true })).toHaveValue('School and dinner with friends')
  for (let index = 0; index < 7; index++) await page.getByRole('button', { name: '← Back', exact: true }).click()
  await expect(page.getByLabel('Email address', { exact: true })).toHaveValue('beta-test@example.com')
  await page.getByRole('button', { name: '← Back', exact: true }).click()
  await expect(page.getByLabel('Your name', { exact: true })).toHaveValue('Jamie')
  expect(outbound).toEqual([])
})

test('final submission returns to an invalid earlier question', async ({ page }) => {
  await page.goto('/beta#before-send')
  await page.getByRole('button', { name: 'Request an invite', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'First, what’s your name?' })).toBeVisible()
  await expect(page.getByLabel('Your name', { exact: true })).toBeFocused()
})

test('the opening title types without shifting and reduced motion reveals it immediately', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/beta')
  const title = page.getByRole('heading', { name: 'Help us make Oro yours.' })
  const letters = title.locator('.beta-type-char')
  await expect(title).toBeVisible()
  await expect(letters.last()).toHaveCSS('opacity', '0')
  await page.evaluate(() => document.fonts.ready)
  const bounds = await title.boundingBox()
  await expect(letters.first()).toHaveCSS('opacity', '1')
  await expect(letters.last()).toHaveCSS('opacity', '1')
  expect(await title.boundingBox()).toEqual(bounds)
  await expect(page.locator('.beta-lead')).toHaveCSS('opacity', '1')
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Help us make Oro yours.' })).toBeVisible()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const letter of await letters.all()) {
    await expect(letter).toHaveCSS('opacity', '1')
    await expect(letter).toHaveCSS('animation-name', 'none')
  }
  await expect(page.locator('.beta-lead')).toHaveCSS('opacity', '1')
  await page.getByRole('link', { name: 'Skip to the form' }).click()
  await expect(page.getByRole('heading', { name: 'First, what’s your name?' })).toBeVisible()
})

test('new pages type their heading and body again when revisited', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/beta')
  await page.getByRole('button', { name: 'Next page', exact: true }).click()
  const title = page.getByRole('heading', { name: 'Our vision is for everyone to have an AI stylist in their corner.' })
  const titleEnd = title.locator('.beta-type-char').last()
  const copyEnd = page.locator('#our-vision .beta-chapter-copy .beta-type-char').last()
  await expect(title).toBeVisible()
  await expect(titleEnd).toHaveCSS('opacity', '0')
  await expect(copyEnd).toHaveCSS('opacity', '0')
  await expect(titleEnd).toHaveCSS('opacity', '1')
  await expect(copyEnd).toHaveCSS('opacity', '1')
  await page.getByRole('button', { name: 'Next page', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Today, we’re testing the earliest version of that experience with you.' })).toBeVisible()
  await expect(page.locator('.beta-story')).toHaveAttribute('data-phase', 'idle')
  await page.getByRole('region', { name: 'About Oro', exact: true }).focus()
  await page.keyboard.press('ArrowLeft')
  await expect(title).toBeVisible()
  await expect(titleEnd).toHaveCSS('opacity', '0')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(titleEnd).toHaveCSS('opacity', '1')
  await expect(copyEnd).toHaveCSS('opacity', '1')
  await expect(titleEnd).toHaveCSS('animation-name', 'none')
})

test('wheel paging animates one page per gesture and supports reverse and reduced motion', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/beta')
  const story = page.locator('.beta-story')
  await page.getByRole('region', { name: 'About Oro', exact: true }).hover()
  await page.mouse.wheel(0, 120)
  await expect(story).toHaveAttribute('data-phase', 'leaving')
  await page.getByRole('region', { name: 'About Oro', exact: true }).evaluate(async (region) => {
    for (let event = 0; event < 32; event++) {
      region.dispatchEvent(new WheelEvent('wheel', { deltaY: 40, bubbles: true, cancelable: true }))
      await new Promise((resolve) => setTimeout(resolve, 40))
    }
  })
  await expect(page.locator('#our-vision')).toBeVisible()
  await expect(story).toHaveAttribute('data-phase', 'idle')
  await expect(page.locator('#our-vision .beta-chapter-content')).toHaveCSS('opacity', '1')
  await expect(page.locator('.beta-chapter')).toHaveCount(1)
  expect(await page.evaluate(() => window.scrollY)).toBe(0)
  await page.mouse.wheel(0, -120)
  await expect(page.getByRole('heading', { name: 'Help us make Oro yours.' })).toBeVisible()
  await expect(story).toHaveAttribute('data-phase', 'idle')
  await page.getByRole('button', { name: 'Next page', exact: true }).click()
  await expect(story).toHaveAttribute('data-phase', 'leaving')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(story).toHaveAttribute('data-phase', 'idle')
  await expect(page.locator('#our-vision')).toBeVisible()
  await expect(page.locator('.beta-chapter-content')).toHaveCSS('animation-name', 'none')
  await page.getByRole('region', { name: 'About Oro', exact: true }).focus()
  await page.keyboard.press('ArrowLeft')
  await expect(page.getByRole('heading', { name: 'Help us make Oro yours.' })).toBeVisible()
})

test('keyboard navigation moves focus and long pages remain scrollable', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/beta')
  await page.getByRole('region', { name: 'About Oro', exact: true }).focus()
  await page.keyboard.press('End')
  await expect(page.locator('#a-little-thank-you-title')).toBeFocused()
  const stage = page.getByRole('region', { name: 'About Oro', exact: true })
  expect(await stage.evaluate((element) => element.scrollHeight > element.clientHeight)).toBe(true)
  await stage.hover()
  await page.mouse.wheel(0, 160)
  await expect.poll(() => stage.evaluate((element) => element.scrollTop)).toBeGreaterThan(0)
  await expect(page.locator('#a-little-thank-you-title')).toBeVisible()
  await page.getByRole('button', { name: 'Request an invite', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'First, what’s your name?' })).toBeFocused()
  await expect(page.getByLabel('Your name', { exact: true })).toBeVisible()
})

test('scrolling forward from the final invitation page opens the form', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/beta')
  const stage = page.getByRole('region', { name: 'About Oro', exact: true })
  await stage.focus()
  await page.keyboard.press('End')
  await expect(page.getByRole('button', { name: 'Go to the form', exact: true })).toBeVisible()
  await stage.hover()
  await page.mouse.wheel(0, 120)
  await expect(page.getByRole('heading', { name: 'First, what’s your name?' })).toBeFocused()
})

test.describe('touch invitation navigation', () => {
  test.use({ hasTouch: true, viewport: { width: 390, height: 844 } })
  test('swipes forward and back without scrolling the document', async ({ page }) => {
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.goto('/beta')
    await expect(page.getByRole('region', { name: 'About Oro', exact: true })).toBeVisible()
    await page.evaluate(() => document.fonts.ready)
    const client = await page.context().newCDPSession(page)
    async function swipe(from, to) {
      await client.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 195, y: from }] })
      await client.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 195, y: to }] })
      await client.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    }
    await swipe(640, 360)
    await expect(page.locator('#our-vision-title')).toBeVisible()
    await swipe(360, 640)
    await expect(page.getByRole('heading', { name: 'Help us make Oro yours.' })).toBeVisible()
    expect(await page.evaluate(() => window.scrollY)).toBe(0)
    await page.getByRole('link', { name: 'Skip to the form' }).click()
    await expect(page.getByRole('heading', { name: 'First, what’s your name?' })).toBeVisible()
  })
})

test('inactive answers are omitted, whitespace is invalid, and text limits apply', () => {
  const answers = { ...emptyAnswers, usualHelpOther: 'Hidden answer', sourceOther: 'Hidden source', genderDescription: 'Hidden description', occasion: '   ', week: 'x'.repeat(2001) }
  expect(visibleAnswers(answers)).not.toHaveProperty('usualHelpOther')
  expect(visibleAnswers(answers)).not.toHaveProperty('sourceOther')
  expect(visibleAnswers(answers)).not.toHaveProperty('genderDescription')
  expect(validateAnswers(answers)).toMatchObject({ occasion: 'Please add an answer.', week: 'Please keep your answer to 2,000 characters.' })
})
