// Generates src/generated/tokens.css from @oro/tokens so the landing's CSS
// variables flow from the design system instead of hand-maintained hex.
// Run: npm run gen:tokens (also runs automatically at the start of `npm run build`).
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { colors, withAlpha, shiftLightness } from '@oro/tokens';

const out = resolve(dirname(fileURLToPath(import.meta.url)), '../src/generated/tokens.css');

// Landing-only derived shades, computed from token bases so they track the
// palette. Factors chosen to approximate the previous hand-picked values
// (plum-soft #4A3560, gold-dim #B89343, gold-light #e8c878).
const plumSoft = shiftLightness(colors.plum, 1.25);
// Interaction colors. The `??` fallbacks are now vestigial — @oro/tokens ships
// primaryActionHoverOnDark/focusRing/hoverTint, and each real token value is
// byte-identical to the fallback it replaced. Kept for resilience.
const hoverOnDark = colors.primaryActionHoverOnDark ?? shiftLightness(colors.plum, 1.5);
const focusRing = colors.focusRing ?? withAlpha(colors.gold, 'B3');
const hoverTint = colors.hoverTint ?? withAlpha(colors.plum, '12');
const goldDim = shiftLightness(colors.gold, 0.8);
const goldLight = shiftLightness(colors.gold, 1.2);

// NOTE the naming shift between the landing vars and token names:
// --oro-cream = token `paper`, --oro-paper = token `white`, --oro-ivory = token `cream`.
// NOTE the CSS below is one big template literal — a backtick inside a comment
// in it terminates the string and breaks the build with a confusing SyntaxError.
const css = `/* GENERATED by scripts/generate-tokens.mjs from @oro/tokens — do not edit.
 * Update tokens in the oro-design-system repo, bump the dep, re-run npm run gen:tokens. */
:root {
  /* ── Raw ORO palette (theme-independent) ── */
  --oro-cream:      ${colors.paper};
  --oro-paper:      ${colors.white};
  --oro-ivory:      ${colors.cream};
  --oro-ink:        ${colors.ink};
  --oro-plum-deep:  ${colors.plum};
  --oro-plum-soft:  ${plumSoft};
  --oro-gold:       ${colors.gold};
  --oro-gold-dim:   ${goldDim};
  /* Small gold text on a light ground. NOT a ramp step: the gold ramp sheds
   * chroma as it darkens, so no step both clears WCAG AA and still reads gold.
   * This is solved for contrast in OKLCh upstream (oro-design-system #22). */
  --oro-accent-text:${colors.accentText};
  --oro-faint:      ${withAlpha(colors.ink, '80')};
  --oro-faintest:   ${withAlpha(colors.ink, '1A')};
  --oro-faint-line: ${withAlpha(colors.ink, '29')};
  --oro-cream-70:   ${withAlpha(colors.paper, 'B3')};
  --oro-cream-45:   ${withAlpha(colors.paper, '73')};
  --oro-cream-line: ${withAlpha(colors.paper, '2E')};

  /* ── Danger / error ──
   * Sourced from the semantic dangerText role rather than the raw rose hex,
   * so a future change to what "danger text" means follows through here. */
  --oro-danger:        ${colors.dangerText ?? colors.rose};
  --oro-danger-surface:${colors.surfaceDanger ?? withAlpha(colors.rose, '14')};
  --oro-danger-border: ${colors.dangerBorder ?? withAlpha(colors.rose, '52')};

  /* ── Interaction (hover/focus — web only) ── */
  --oro-hover:         ${colors.primaryActionHover ?? shiftLightness(colors.plum, 0.88)};
  --oro-hover-on-dark: ${hoverOnDark};
  --oro-hover-tint:    ${hoverTint};
  --oro-focus-ring:    ${focusRing};

  /* ── Type ── */
  --font-serif: "Fraunces", "Cormorant Garamond", serif;
  --font-sans:  "Inter", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif;

  /* ── Legacy aliases (older stylesheets) ── */
  --ink: ${colors.ink};
  --stone: #8a8a86;
  --purple: ${colors.plum};
  --purple-deep: ${colors.plum};
  --purple-soft: ${plumSoft};
  --gold: ${colors.gold};
  --gold-light: ${goldLight};
  --gold-muted: ${withAlpha(colors.gold, '8C')};
}
`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, css);
console.log(`wrote ${out}`);
